"""new version of models

Revision ID: c52b6337bbe1
Revises: ed6553e11bbe
Create Date: 2024-05-01 19:17:55.864749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52b6337bbe1'
down_revision = 'ed6553e11bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ndc_id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('insurance',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.alter_column('pharmacy',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('drug_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pharmacist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.alter_column('pharmacist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('drug_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.alter_column('pharmacy',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('insurance',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
